
// Generated by Wrangler on Fri Dec 06 2024 14:13:12 GMT-0600 (Central Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	DB: D1Database;
}
