// Generated by Wrangler on Thu Jul 04 2024 15:04:42 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	DB: D1Database;
}
